import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-gift-card-breakage-settlement-reconciliation",
  "engine": "recovery",
  "title": "Gift Card Breakage & Settlement Reconciliation",
  "shortTitle": "Gift Card Breakage and Settlement Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through gift card breakage & settlement reconciliation",
  "industry": "Stored Value Financial Control",
  "uiPort": 4621,
  "apiPort": 5621,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Gift Card Breakage & Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "settledValue",
    "expectedKey": "supportedValue",
    "actualLabel": "Settled and Recognized Value",
    "expectedLabel": "Supported Liability and Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Gift Card Breakage & Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("program-processor-agreements","GCB01","Program processor agreements","Execute program processor agreements using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed program processor agreements decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Program processor agreements Reference","text","GCB01-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("card-issuance-ledger","GCB02","Card issuance ledger","Execute card issuance ledger using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed card issuance ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Card issuance ledger Reference","text","GCB02-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("activation-reconciliation","GCB03","Activation reconciliation","Execute activation reconciliation using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed activation reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Activation reconciliation Reference","text","GCB03-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("redemption-ingestion","GCB04","Redemption ingestion","Execute redemption ingestion using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed redemption ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Redemption ingestion Reference","text","GCB04-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("multi-brand-settlement","GCB05","Multi-brand settlement","Execute multi-brand settlement using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed multi-brand settlement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Multi-brand settlement Reference","text","GCB05-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("merchant-funding-calculation","GCB06","Merchant funding calculation","Execute merchant funding calculation using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed merchant funding calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Merchant funding calculation Reference","text","GCB06-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("processor-fee-audit","GCB07","Processor fee audit","Execute processor fee audit using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed processor fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Processor fee audit Reference","text","GCB07-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("fraud-duplicate-redemption","GCB08","Fraud duplicate redemption","Execute fraud duplicate redemption using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed fraud duplicate redemption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Fraud duplicate redemption Reference","text","GCB08-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("refund-replacement-control","GCB09","Refund replacement control","Execute refund replacement control using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed refund replacement control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Refund replacement control Reference","text","GCB09-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("breakage-estimation","GCB10","Breakage estimation","Execute breakage estimation using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed breakage estimation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Breakage estimation Reference","text","GCB10-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("recognition-schedules","GCB11","Recognition schedules","Execute recognition schedules using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed recognition schedules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Recognition schedules Reference","text","GCB11-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("unclaimed-property-classification","GCB12","Unclaimed property classification","Execute unclaimed property classification using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed unclaimed property classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Unclaimed property classification Reference","text","GCB12-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("partner-settlement-reconciliation","GCB13","Partner settlement reconciliation","Execute partner settlement reconciliation using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed partner settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Partner settlement reconciliation Reference","text","GCB13-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("cash-liability-reconciliation","GCB14","Cash liability reconciliation","Execute cash liability reconciliation using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed cash liability reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Cash liability reconciliation Reference","text","GCB14-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]}),
feature("program-analytics","GCB15","Program analytics","Execute program analytics using gift card program agreements, card issuance, activation, redemption, multi-brand settlements, processor fees, refunds, replacements, breakage, unclaimed property, and accounting entries.","Produce a governed program analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Gift Card Portfolio","text","Program / Gift Card Portfolio · Standard Case"],["caseReference","Program analytics Reference","text","GCB15-2026-001"],["settledValue","Settled and Recognized Value","currency",975000],["supportedValue","Supported Liability and Revenue","currency",1150500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledValue",subjects:["Program processor agreements case","Card issuance ledger case","Activation reconciliation case","Redemption ingestion case","Multi-brand settlement case"]})
]);
